"""Shared semantic extraction and source-diagnostic handling."""

import re
from datetime import timedelta
from decimal import Decimal, InvalidOperation
from pathlib import PurePosixPath
from urllib.parse import urlsplit

from bs4 import BeautifulSoup, Tag

from ...errors import ParseError
from .. import keys
from ..models import (
    BreakdownEntry,
    BreakdownSeries,
    DisplayValue,
    Entity,
    MetricEntry,
    MetricSeries,
    Number,
    ReportIssue,
    ReportMetadata,
    ReportOverview,
)

BREAKDOWNS = {
    "Score source": keys.SCORE_SOURCES,
    "Coins source": keys.COINS_SOURCES,
    "Experience": keys.EXPERIENCE_SOURCES,
    "Loot": keys.LOOT,
}
METRICS = {
    "By count": keys.TOWER_COUNT,
    "By upgrade level": keys.TOWER_UPGRADE_LEVELS,
    "By XP level": keys.TOWER_XP_LEVELS,
    "By MDPS (one tower)": keys.TOWER_MDPS,
    "By kills": keys.TOWER_KILLS,
    "By damage": keys.TOWER_DAMAGE,
    "By money spent": keys.TOWER_MONEY_SPENT,
    "Damage per coin": keys.TOWER_DAMAGE_PER_COIN,
    "Kills per coin": keys.TOWER_KILLS_PER_COIN,
    "Towers sold": keys.TOWER_SALES,
    "Resources gained": keys.RESOURCE_GAINED,
    "Miners - built": keys.MINER_COUNT,
    "Miners - upgraded": keys.MINER_UPGRADE_LEVELS,
    "Miners - money spent": keys.MINER_MONEY_SPENT,
    "Passed enemies": keys.ENEMY_PASSED,
    "Enemies buffed": keys.ENEMY_BUFFS,
    "Enemies killed by": keys.ENEMY_KILLS_BY_SOURCE,
    "Abilities": keys.ABILITY_USAGE,
    "Modifiers": keys.MODIFIER_USAGE,
}
GENERAL = {
    "Towers built": keys.GENERAL_TOWERS_BUILT,
    "Towers sold": keys.GENERAL_TOWERS_SOLD,
    "Resources gained": keys.GENERAL_RESOURCES_GAINED,
    "Enemies killed": keys.GENERAL_ENEMIES_KILLED,
    "Enemies passed": keys.GENERAL_ENEMIES_PASSED,
    "Time saved by wave calls (s)": keys.GENERAL_WAVE_CALL_TIME_SAVED_SECONDS,
    "Enemies buffed": keys.GENERAL_ENEMIES_BUFFED,
    "Max miners built sim.": keys.GENERAL_MAX_MINERS_BUILT_SIMULTANEOUSLY,
    "Max towers built sim.": keys.GENERAL_MAX_TOWERS_BUILT_SIMULTANEOUSLY,
}
ECONOMY = {
    "On towers": keys.ECONOMY_SPENT_ON_TOWERS,
    "On miners": keys.ECONOMY_SPENT_ON_MINERS,
}
ALIASES = {
    "Generated by towers": "GENERATED",
    "Enemies damaged / killed": "KILLED_ENEMIES",
    "Total bit dust": "BIT_DUST",
}


def entity(label: str, asset_name: str | None = None) -> Entity:
    """Normalize readable names, retaining distinct source labels."""
    key = ALIASES.get(label, re.sub(r"[\s/-]+", "_", label.upper()))
    return Entity(key, label if key != label else None, asset_name)


def asset(tag: Tag) -> str | None:
    src = tag.get("src")
    return PurePosixPath(urlsplit(str(src)).path).name if src else None


def number(text: str) -> Number:
    display = text.strip()
    clean = display.replace(",", "").replace("\u00a0", "")
    match = re.fullmatch(r"([+-]?(?:\d+(?:\.\d*)?|\.\d+))([KMBT%]?)", clean)
    if not match:
        raise ParseError(f"Invalid numeric value: {display!r}")
    base, suffix = match.groups()
    value = Decimal(base) if "." in base else int(base)
    if suffix:
        factors: dict[str, int | Decimal] = {
            "K": 1000,
            "M": 1000000,
            "B": 1000000000,
            "T": 1000000000000,
            "%": Decimal("0.01"),
        }
        return DisplayValue(value * factors[suffix], display)
    return value


def numeric(value: Number) -> int | Decimal:
    return value.value if isinstance(value, DisplayValue) else value


def integer(text: str) -> int:
    value = number(text)
    if type(value) is not int:
        raise ParseError(f"Expected an exact integer: {text!r}")
    return value


def elapsed(text: str) -> timedelta:
    match = re.fullmatch(
        r"\s*((?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?)\s*([smh])\s*", text
    )
    if not match:
        raise ParseError(f"Invalid elapsed time: {text!r}")
    value = (
        Decimal(match[1].replace(",", ""))
        * {"s": 1, "m": 60, "h": 3600}[match[2]]
        * 1000000
    )
    if value != value.to_integral_value():
        raise ParseError("Elapsed time exceeds timedelta precision")
    return timedelta(microseconds=int(value))


class Page:
    def __init__(self, html: str, source_url: str):
        self.source_url = source_url
        self.issues: list[ReportIssue] = []
        # PHP diagnostics are not statistical fields. Remove only their bounded
        # diagnostic markup, including occurrences inside chart array literals.
        diagnostic = re.compile(
            r"<b>(?:Notice|Warning|Deprecated|Fatal error)</b>\s*:.*?<br\s*/?>",
            re.S | re.I,
        )

        def remove(match: re.Match) -> str:
            headings = re.findall(
                r"<h[23][^>]*>(.*?)</h[23]>", html[: match.start()], re.S
            )
            heading = (
                BeautifulSoup(headings[-1], "html.parser").get_text()
                if headings
                else "source"
            )
            section = BREAKDOWNS.get(heading, METRICS.get(heading, heading))
            message = BeautifulSoup(match[0], "html.parser").get_text(" ", strip=True)
            message = re.split(r"\s+in\s+", message, maxsplit=1)[0]
            self.issues.append(ReportIssue(keys.UPSTREAM_DIAGNOSTIC, section, message))
            return ""

        self.soup = BeautifulSoup(diagnostic.sub(remove, html), "html.parser")
        self.consumed_bars: set[int] = set()

    def heading(self, name: str) -> Tag | None:
        found = self.soup.find(["h2", "h3"], string=lambda s: s and s.strip() == name)
        return found if isinstance(found, Tag) else None

    def metadata(self) -> ReportMetadata:
        found = re.search(r"Report generated in\s+([\d.]+)s", self.soup.get_text(" "))
        try:
            seconds = Decimal(found[1]) if found else None
        except InvalidOperation as exc:
            raise ParseError("Invalid report generation duration") from exc
        return ReportMetadata(self.source_url, seconds, tuple(self.issues))

    def bars(self, container: Tag) -> list[Tag]:
        bars = container.select(".horizontal-bar-wrap")
        self.consumed_bars.update(id(bar) for bar in bars)
        return bars

    def audit_bars(self) -> None:
        if any(
            id(bar) not in self.consumed_bars
            for bar in self.soup.select(".horizontal-bar-wrap")
        ):
            raise ParseError("Unrecognized statistical section; parser update required")


def labeled_value(bar: Tag) -> tuple[str, str]:
    span = bar.find("span", recursive=False)
    if span is None:
        raise ParseError("Missing statistical value")
    label, separator, value = span.get_text(" ", strip=True).rpartition(":")
    if not separator:
        raise ParseError("Missing statistical label")
    return label.strip(), value.strip()


def percent(text: str, page: Page, section: str) -> Decimal | None:
    try:
        if not text.endswith("%"):
            raise ParseError("Missing percentage unit")
        return Decimal(numeric(number(text)))
    except ParseError:
        page.issues.append(
            ReportIssue(keys.INVALID_NUMBER, section, "Invalid source percentage")
        )
        return None


def parse_breakdown(page: Page, container: Tag, key: str) -> BreakdownSeries:
    entries: list[tuple[Entity, Number, str]] = []
    for bar in page.bars(container):
        label, raw_value = labeled_value(bar)
        display = bar.select_one(".horizontal-bar")
        share_text = display.get_text(strip=True) if display else ""
        entries.append((entity(label), number(raw_value), share_text))
    total = sum((numeric(value) for _, value, _ in entries), 0) if entries else None
    result = []
    for item, value, share_text in entries:
        share = Decimal(numeric(value)) / Decimal(total) if total else None
        displayed = percent(share_text, page, key) if share_text else None
        display_share = None
        if displayed is not None:
            if share is None:
                display_share = displayed
            else:
                precision = Decimal(share_text.rstrip("%")).as_tuple().exponent
                assert isinstance(precision, int)  # percent() accepted a finite number
                rounded = (share * 100).quantize(Decimal(1).scaleb(precision)) / 100
                if rounded != displayed:
                    display_share = displayed
        result.append(BreakdownEntry(item, value, share, display_share))
    return BreakdownSeries(key, total, tuple(result))


def parse_overview(page: Page, table: Tag | None) -> ReportOverview:
    score = BreakdownSeries(keys.SCORE_SOURCES, None, ())
    coins = BreakdownSeries(keys.COINS_SOURCES, None, ())
    towers = MetricSeries(keys.TOWER_MONEY_SPENT, ())
    modifiers = MetricSeries(keys.MODIFIER_USAGE, ())
    research = play_time = duration = None
    if table is None:
        return ReportOverview(score, coins, towers, modifiers)
    row = table.select_one("tr")
    if row is None:
        raise ParseError("Malformed compact overview")
    for cell in row.find_all("td", recursive=False):
        icon = cell.select_one(".title-icon")
        if icon is None:
            raise ParseError("Unrecognized compact overview field")
        name = asset(icon)
        breakdown_entries: list[BreakdownEntry] = []
        metric_entries: list[MetricEntry] = []
        for image in cell.find_all("img"):
            if image is icon or asset(image) == "blank.png":
                continue
            title = image.get("title", "")
            label, sep, value = str(title).rpartition(":")
            if not sep:
                raise ParseError("Missing overview entity value")
            item = entity(label.strip(), asset(image))
            if name in ("icon-star.png", "icon-coin.png"):
                breakdown_entries.append(
                    BreakdownEntry(item, None, percent(value.strip(), page, "overview"))
                )
            else:
                metric_entries.append(
                    MetricEntry(item, number(value.strip().removesuffix(" coins")))
                )
        if name == "icon-star.png":
            score = BreakdownSeries(keys.SCORE_SOURCES, None, tuple(breakdown_entries))
        elif name == "icon-coin.png":
            coins = BreakdownSeries(keys.COINS_SOURCES, None, tuple(breakdown_entries))
        elif name == "icon-tower.png":
            towers = MetricSeries(keys.TOWER_MONEY_SPENT, tuple(metric_entries))
        elif name == "icon-modifier.png":
            modifiers = MetricSeries(keys.MODIFIER_USAGE, tuple(metric_entries))
        elif name == "icon-research.png":
            values = list(cell.stripped_strings)
            if len(values) > 2:
                raise ParseError("Unrecognized research overview values")
            research = number(values[0]) if values else None
            play_time = elapsed(values[1]) if len(values) == 2 else None
        elif name == "icon-clock.png":
            value = cell.get_text(strip=True)
            duration = elapsed(value) if value else None
        else:
            raise ParseError(f"Unrecognized overview field: {name}")
    return ReportOverview(
        score, coins, towers, modifiers, research, play_time, duration
    )


def info_fields(page: Page, allowed: set[str]) -> dict[str, str]:
    fields = {}
    for row in page.soup.select("table.replay-info tr"):
        cells = row.find_all("td", recursive=False)
        if len(cells) != 2:
            raise ParseError("Malformed report information row")
        label, value = (cell.get_text(" ", strip=True) for cell in cells)
        if label not in allowed or label in fields:
            raise ParseError(f"Unrecognized or duplicate report information: {label}")
        fields[label] = value
    return fields
